### PR TITLE
Acj args source fix

### PR DESCRIPTION
**Pull request by blow05**
When I set <complianceLevel>21</complianceLevel> in my pom.xml I recieve error:
AJC compiler errors: error unrecognized single argument: "-21"

This change should fix this issue

### CODE REVIEW

**Comment by blow05** [comment]
I've created branch from tags/1.15, but I can't specify tag as pull request target

**Comment by kriegaex** [comment]
Thanks for your contribution, but

1. it contains 105 commits, because you seem to have branched it off of an old version,
2. it is unnecessary, because reading the [documentation](https://dev-aspectj.github.io/aspectj-maven-plugin/usage.html#upgrading_or_downgrading_aspectj) and simply upgrading the `aspectjtools` plugin dependency fixes the problem.

Besides, you either use `complianceLevel` (if source and target are the same) or `source` and `target` (if they are different) to configure the AspectJ compiler, not some random combination like `complianceLevel` and `source`.

FYI, some of the improvements of this fork compared to the MojoHaus version also mentioned in the [read-me right on the front page](https://github.com/dev-aspectj/aspectj-maven-plugin?tab=readme-ov-file#feature-comparison-mojohaus-vs-aspectjdev) of this project are that
* new Java versions for source, target and release do not have to be added to the code manually and therefore no code change is necessary for every new AspectJ release,
* you do not need to set source and target on top of compliance level to avoid errors like in the Mojohaus version.

**Comment by blow05** [comment]
Thanks for the quick and detailed response.
But check please this commit: https://github.com/dev-aspectj/aspectj-maven-plugin/pull/148/commits/f5f7d6d7cb7b508a74ff0d241402ba6a0a76326a

I think, there is issue that should be fixed. Same issue persists in master branch. Should I create new pull request from master for this fix?

**Comment by kriegaex** [comment]
To me, this change makes no sense. Which problem is it supposed to solve?

**Comment by blow05** [comment]
It should fix error:
AJC compiler errors: error unrecognized single argument: "-21"

**Comment by kriegaex** [comment]
No, upgrading `aspectjtools` in your plugin config to a compiler version actually knowing the parameter does. Trust me, I tried. No change is necessary, it would even be a bug to change it like that. You should read my messages more carefully and follow the links to the documentation.

**Comment by blow05** [comment]
Ok, but there is next code in https://github.com/dev-aspectj/aspectj-maven-plugin/blob/main/src/main/java/org/codehaus/mojo/aspectj/AjcReportMojo.java :
just FYI
 public void setComplianceLevel( String complianceLevel )
    {
        if ( AjcHelper.isValidComplianceLevel( complianceLevel ) )
        {
            ajcOptions.add( "-source" );
            ajcOptions.add( complianceLevel );
        }
    }

**Comment by kriegaex** [comment]
I improved that part of the MojoHaus code long ago. This piece of code looks wrong to me. I will not copy it without any good reason. This fork works with Java 21, no matter if you use `source` and `target` or `complianceLevel`. Like I said, I tried. It also works with `release` which, last time I checked, is not even available in the MojoHaus version.

I suggest to either rest your case or provide a reproducer showing what you think is the problem in this fork that is solved by your suggested change. If there is evidence, I might consider reopening the PR. But presently, I believe the change would simply do harm.

**Pull request closed without merging**
