### PR TITLE
[#5] Remove tools.jar dependency, fix ITs, mrm-maven-plugin, plugin updates

### LINKED ISSUE #5: Cannot build using Java9+
https://github.com/bmarwell/aspectj-maven-plugin/actions/runs/881364653

e.g.
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site (default-site) on project aspectj-maven-plugin: failed to get report for org.codehaus.mojo:cobertura-maven-plugin: Plugin org.codehaus.mojo:cobertura-maven-plugin:2.6 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:0 at specified path /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/../lib/tools.jar -> [Help 1]
```

Guess: hard dependency on `tools.jar` instead of using `ToolProvider`.
JDK9+ changed layouts.

### PR DESCRIPTION
**Pull request by bmarwell**
Fixes #5. 

Granted, this commit does a little too much:

* Use mrm maven plugin instead of repo-local like the ASF does.
* Moving ITs to to src/it/projects which is almost a convention in ASF projects.
* Proper IT plugins execution order
* updated some plugins so they play together nicely on newer JDKs

### CODE REVIEW

**Comment by kriegaex** [comment]
@bmarwell, I was also working on sorting out some dependency and plugin issues in a local branch, at least in between my daytime job and private things. Maybe it would make sense to coordinate our efforts a bit. Are you using Gitter or Telegram? My user name is always kriegaex.

**Comment by kriegaex** [comment]
Actually, I cannot reproduce the problem you have in your builds. It also is not happening in our GitHub builds, after I accepted your PR with my modifications and some POM improvements I did before. The tools.jar dependency is still in for Java 8 only, just like before. The problem in #5 must have come from somewhere else. Therefore, I am not merging this as is.

You might want to rebase on master first, then strip down the PR to the other improvements or just open a new one, whatever you prefer.

**Comment by kriegaex** [comment]
Oh, I am so sorry that you felt you had to close this PR instead of updating it. I think there were several good things in it. I would have wished you refine it and we can get it merged. But I guess, you are boycotting this repository already, regrettably.

**Comment by bmarwell** [comment]
I'm not boycotting it. Feel free to cherry-pick what you need!
Btw, I rather would have opened a new one anyway.

**Pull request closed without merging**
